# Generated by Django 4.2 on 2024-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_contactus_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
